{
 "title": "loki-system",
 "description": "Gemcloud Logging System Metrics via by loki",
 "tags": [
  "loki",
  "logging",
  "plugin"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Loki Global Metrics</span>\n</div>"
   },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_build_info{job=\"loki-headless\"}"
    }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_log_messages_total{job=\"loki-headless\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc (sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kubegems-logging\",pod=~\"loki.*\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_rss{namespace=\"kubegems-logging\",pod=~\"loki-.*\",container!=\"\",image!~\".*exporter.*\"} )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{job=\"loki-headless\"})"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{job=\"loki-headless\"})"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{job=~\"loki.*\"}[5m])) by (le,route,job))",
     "legendFormat": "{{job}} ~ {{ route }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{job=\"loki-headless\"}[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{job=\"loki-headless\"}[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Rules Status ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_prometheus_rule_evaluations_total{job=\"loki-headless\"})",
     "legendFormat": "Evaluations"
    },
    {
     "expr": "sum(cortex_prometheus_notifications_sent_total{job=\"loki-headless\"})",
     "legendFormat": "Notifications"
    }
   ]
  },
  {
   "title": "Notifications Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_prometheus_notifications_latency_seconds{job=\"loki-headless\"}[5m]))  by (quantile)",
     "legendFormat": "TP {{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_prometheus_rule_evaluation_duration_seconds{job=\"loki-headless\"}[5m]))  by (quantile)",
     "legendFormat": "TP {{quantile}}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Lines / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total{job=\"loki-headless\"}[5m]))",
       "legendFormat": "distributor / {{ tenant}}"
      }
     ]
    },
    {
     "title": "Distributor  Received bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"loki-headless\"}[5m])) by (tenant)",
       "legendFormat": "distributor / {{tenant}}"
      }
     ]
    },
    {
     "title": "batch appends sent to ingesters / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_appends_total{job=\"loki-headless\"}[5m])",
       "legendFormat": "successed"
      },
      {
       "expr": "loki_distributor_ingester_append_failures_total{job=\"loki-headless\"}",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Store Series / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(loki_store_series_total{job=\"loki-headless\"}[5m]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Ingster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Blocks / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{job=\"loki-headless\"}[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(rate(loki_ingester_chunks_created_total{job=\"loki-headless\"}[5m]))",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{job=\"loki-headless\"}[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{job=\"loki-headless\"})",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams{job=\"loki-headless\"})",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Strams Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_created_total{job=\"loki-headless\"}[5m]))",
     "legendFormat": "create"
    },
    {
     "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"loki-headless\"}[5m]))",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}