{
 "title": "PAI",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gnode",
    "query": {
     "query": "label_values(kube_node_info{node!~\"ceph.*\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总算力 FP64",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL) * 9.6",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "总显卡数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_POWER_USAGE{})"
    }
   ]
  },
  {
   "title": "总任务",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(pai_job_info)" }
   ]
  },
  {
   "title": "数据集",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pai_pvc_info{bucket=~\"dataset.*\"})"
    }
   ]
  },
  {
   "title": "模型集",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pai_pvc_info{bucket=~\"model.*\"})"
    }
   ]
  },
  {
   "title": "个人空间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pai_pvc_info{bucket=~\"workspace.*\"})"
    }
   ]
  },
  {
   "title": "GPU 闲置",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{pod=~''})",
     "legendFormat": "空闲GPU"
    }
   ]
  },
  {
   "title": "实时 FP64",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(9.6 * count(DCGM_FI_DEV_GPU_UTIL)) * avg(DCGM_FI_DEV_GPU_UTIL) / 100",
     "legendFormat": "实时算力"
    }
   ]
  },
  {
   "title": "使用中的GPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_POWER_USAGE{pod!~''})"
    }
   ]
  },
  {
   "title": "闲置GPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_POWER_USAGE{pod=~''})"
    }
   ]
  },
  {
   "title": "文件数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pai_storageset_total_files)"
    }
   ]
  },
  {
   "title": "容量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pai_storageset_total_capability)"
    }
   ]
  },
  {
   "title": "$gnode显卡运行状态",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "pai_job_gpu_utils{node=\"$gnode\"}"
    }
   ]
  },
  {
   "title": "$gnode 任务状态",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "sum(gems_container_cpu_usage_percent{namespace=\"kubegems-pai\",node=\"$gnode\"}) by (pod)",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(gems_container_memory_usage_percent{namespace=\"kubegems-pai\",node=\"$gnode\"}) by (pod)",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "主机实时状态",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (gems_node_load1{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_load15{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_cpu_usage_percent{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_memory_usage_percent{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_disk_usage_percent{node!~\"ceph.*\",device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"})"
    },
    {
     "expr": "sum by (node) (gems_node_disk_read_bps{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_disk_write_bps{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_network_receive_bps{node!~\"ceph.*\"})"
    },
    {
     "expr": "sum by (node) (gems_node_network_send_bps{node!~\"ceph.*\"})"
    },
    {
     "expr": "count by (node) (pai_job_gpu_temp{pod!=\"\"})",
     "legendFormat": "空闲GPU"
    },
    {
     "expr": "sum by (node) (pai_job_gpu_utils) / count by (node) (pai_job_gpu_temp)",
     "legendFormat": "GPU使用率"
    },
    {
     "expr": "sum by (node) (pai_job_gpu_mem_utils) / count by (node) (pai_job_gpu_temp)",
     "legendFormat": "GPU显存"
    },
    {
     "expr": "max by (node) (pai_job_gpu_temp)",
     "legendFormat": "GPU温度"
    },
    {
     "expr": "sum by (node) (pai_job_gpu_power)",
     "legendFormat": "功率"
    },
    {
     "expr": "sum by (node) (sum_over_time(pai_job_gpu_power{node!~\"ceph.*|\"}[1d])/2880) *24",
     "legendFormat": "过去1天功率"
    }
   ]
  },
  {
   "title": "$gnode GPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pai_job_gpu_utils{node=\"$gnode\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$gnode GPU内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pai_job_gpu_mem_utils{node=\"$gnode\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$gnode  GPU温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "pai_job_gpu_temp{node=\"$gnode\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU 总能耗",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE)", "legendFormat": "总功率" }
   ]
  }
 ]
}